##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/libcafekbd
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gettext
    - git
    - gobject-introspection
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libtool
    - libxklavier-dev
    - libxml2-utils
    - make
    - wget

    #packages required for ctk
    - adwaita-icon-theme
    - dconf-gsettings-backend
    - gir1.2-atk-1.0
    - hicolor-icon-theme
    - libatk-bridge2.0-0
    - libatk-bridge2.0-dev
    - libcolord2
    - libcups2
    - libegl1-mesa-dev
    - libepoxy0
    - libepoxy-dev
    - libfontconfig1-dev
    - libfribidi-dev
    - libgdk-pixbuf2.0-dev
    - libjson-glib-1.0-0
    - libpango1.0-dev
    - librest-0.7-0
    - libwayland-dev
    - libxcomposite-dev
    - libxcursor-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - libxrandr-dev
    - wayland-protocols

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-debs https://github.com/cafe-desktop/ctk master libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-icon-theme/raw/master/cafe/16x16/devices/input-keyboard.png; fi
